### ISSUE TITLE
SuCreateAppContainerToken 函数 Bug?

### ISSUE THREAD

**Issue by MeeSong** [M2Team/M2-SDK#2]
根据我对 CreateProcessInternalW 的逆向来看.

# Bug-1
`SuCreateAppContainerToken ` 函数中调用 `NtCreateLowBoxToken` 函数的参数有些差异.

1. AccessMask 参数不一致
2. 没有传入 OBJECT_ATTRIBUTES 

```C
status = pNtCreateLowBoxToken(
    TokenHandle,
    ExistingTokenHandle,
    MAXIMUM_ALLOWED,
    nullptr,
    SecurityCapabilities->AppContainerSid,
    SecurityCapabilities->CapabilityCount,
    SecurityCapabilities->Capabilities,
    6,
    HandleList);
```

![lowbox1](https://user-images.githubusercontent.com/6848759/27443069-9a7c9456-57a4-11e7-8434-4ee77df93b36.jpg)

# Bug-2

`SuCreateAppContainerToken ` 函数中调用 `NtCreateFile` 函数创建命名管道的参数有些差异.

1. AccessMask 参数不一致

```C
status = NtCreateFile(
	&HandleList[SuAppContainerHandleList::NamedPipe],
    SYNCHRONIZE | STANDARD_RIGHTS_REQUIRED |
	FILE_WRITE_DATA | FILE_CREATE_PIPE_INSTANCE,
	&ObjectAttributes,
	&IoStatusBlock,
    nullptr,
    FILE_ATTRIBUTE_NORMAL,
    FILE_SHARE_READ | FILE_SHARE_WRITE,
    FILE_OPEN_IF,
    FILE_DIRECTORY_FILE,
    nullptr,
    0);
```

![lowbox2](https://user-images.githubusercontent.com/6848759/27443404-7c1c4410-57a5-11e7-9df1-e7517987e390.jpg)

PIPE_ALL_ACCESS 的定义如下

```C
#define PIPE_ALL_ACCESS (SYNCHRONIZE \
            | STANDARD_RIGHTS_REQUIRED \
            | PIPE_ACCESS_INBOUND \
            | PIPE_ACCESS_OUTBOUND \
            | PIPE_ACCESS_DUPLEX)
```

**Comment by MouriNaruto** [comment]
管道的这个魔数原来是这个值啊

关于NtCreateLowBoxToken，不传入ObjectAttributes在实践上也是可行的（但既然微软的二进制指定了……那我也跟进把）

**Comment by MouriNaruto** [comment]
已修复
